version: 0.0
os: linux
files:
  - source: /public
    destination: /var/www/html/public
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 60
      runas: root
    - location: scripts/start_server
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 60
      runas: root

