# values should be populated from the .env using the follow command `terraform [comman] [options]] -var-file=.env`
variable "APP_ENV" {}
variable "APP_NAME" {}
variable "AWS_ACCESS_KEY" {}
variable "AWS_PEM_KEY_PAIR" {}
variable "AWS_REGION" {}
variable "AWS_S3_MEDIA_DISPLAY_BUCKET" {}
variable "AWS_S3_MEDIA_SOURCE_BUCKET" {}
variable "AWS_SECRET_KEY" {}
variable "CONTACT_EMAIL" {}
variable "DB_HOST" {}
variable "DB_PASS" {}
variable "DB_SCHE" {}
variable "DB_USER" {}
variable "SES_SMTP_ADDRESS" {}
variable "SES_SMTP_PORT" {}
variable "SES_SMTP_SENDER" {}
variable "SES_SMTP_USERNAME" {}
variable "SES_SMTP_PASSWORD" {}
