---
- hosts: all
  vars:
    AWS_ACCESS_KEY: ""
    AWS_SECRET_KEY: ""
  become: true
  gather_facts: false

  # pre_tasks:
  #   - name: Update dependencies via apt-get
  #     raw: apt-get clean && apt-get autoclean && apt autoremove -y && apt-get update -y

  #   - name: Installing awscli, https transport, build-essential, Python & PIP
  #     raw: apt-get install -y awscli apt-transport-https build-essential python-minimal python-setuptools python-pip software-properties-common

  tasks:
    # - name: Install system dependencies
    #   apt:
    #     pkg:
    #       - automake
    #       - autotools-dev
    #       - fuse
    #       - g++
    #       - git
    #       - libcurl4-gnutls-dev
    #       - libfuse-dev
    #       - libssl-dev
    #       - libxml2-dev
    #       - make
    #       - pkg-config
    #     state: present

    # - git:
    #     accept_hostkey: yes
    #     remote: origin
    #     depth: 1
    #     dest: /home/ubuntu/s3fs-fuse
    #     repo: https://github.com/s3fs-fuse/s3fs-fuse.git
    #     version: master
    #     force: true

    # - lineinfile:
    #     create: true
    #     line: "{{AWS_ACCESS_KEY}}:{{AWS_SECRET_KEY}}"
    #     path: /etc/passwd-s3fs
    #     state: present
    #     owner: ubuntu
    #     group: ubuntu
    #     mode: 0600

    - name: Compile and use S3FS to mount a bucket
      command: > 
        cd s3fs-fuse
        ./autogen.sh
        ./configure --prefix=/usr --with-openssl
        make
        make install
        which s3fs
        cd ../
        mkdir ./testing
        s3fs poc-media-tst-1fb3fdcb-8789-0844-e364-06a1b4bcf3cf -o use_cache=/tmp -o allow_other -o uid=1001 -o mp_umask=002 -o multireq_max=5 ./testing
