default: &default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4
  host: <%= ENV['RDS_DB_HOST'] %>
  password: <%= ENV['RDS_DB_PASS'] %>
  pool: 5
  port: <%= ENV['RDS_DB_PORT'] %>
  reconnect: true
  username: <%= ENV['RDS_DB_USER'] %>

development:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
