default: &default
  adapter: mysql2
  host: <%= ENV['RDS_DB_HOST'] %>
  port: <%= ENV['RDS_DB_PORT'] %>
  username: <%= ENV['RDS_DB_USER'] %>
  password: <%= ENV['RDS_DB_PASS'] %>
  encoding: utf8
  pool: 5
  reconnect: true

development:
  <<: *default
  database: <%= ENV['RDS_DB_SCHE'] %>

test:
  <<: *default
  database: <%= ENV['RDS_DB_SCHE'] %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_SCHE'] %>
