# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

test:
  secret_key_base: 68a0b0beaad7569ecc326f36560b8fa88d4b4f4dac99f09a56aed3bd784683179e8e811379b03b114061c3b092df0cc92e949413ebdb0d0e30b68f5330a281ec
  # secret_key_base: <%= ENV['COOKIE_TST_SECRET_KEY'] %>

development:
  secret_key_base: 0595c502fe5b56f8ece615e31484847dae7f5c16bbace7583755c405730a9c0acac1319a0e1a895742c714054def76a99265291514abca8d7e8419f1dfd2f337
  # secret_key_base: <%= ENV['COOKIE_DEV_SECRET_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # DO NOT STORE PRD COOKIE SECRET KEY!
  secret_key_base: <%= ENV['COOKIE_PRD_SECRET_KEY_BASE'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
