# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

   
campus_category = Category.where(name: 'campus').first_or_create!(name: 'campus')
community_category = Category.where(name: 'community').first_or_create!(name: 'community')
housing_category = Category.where(name: 'housing').first_or_create!(name: 'housing')
h2f_category = Category.where(name: 'h2f').first_or_create!(name: 'h2f')
free_category = Category.where(name: 'free').first_or_create!(name: 'free')
jobs_category = Category.where(name: 'jobs').first_or_create!(name: 'jobs')
talent_category = Category.where(name: 'talent').first_or_create!(name: 'talent')
personals_category = Category.where(name: 'personals').first_or_create!(name: 'personals')
sale_category = Category.where(name: 'sale').first_or_create!(name: 'sale')
services_category = Category.where(name: 'services').first_or_create!(name: 'services')
unboxing_category = Category.where(name: 'unboxing').first_or_create!(name: 'unboxing')




Subcategory.where(name: 'Activities & Events', category_id: campus_category.id).first_or_create!(name: 'Activities & Events', category_id: campus_category.id)
Subcategory.where(name: 'Jobs', category_id: campus_category.id).first_or_create!(name: 'Jobs', category_id: campus_category.id)
Subcategory.where(name: 'Furniture', category_id: campus_category.id).first_or_create!(name: 'Furniture', category_id: campus_category.id)
Subcategory.where(name: 'Electronics', category_id: campus_category.id).first_or_create!(name: 'Electronics', category_id: campus_category.id)
Subcategory.where(name: 'Books', category_id: campus_category.id).first_or_create!(name: 'Books', category_id: campus_category.id)
Subcategory.where(name: 'Activities', category_id: campus_category.id).first_or_create!(name: 'Activities', category_id: campus_category.id)
Subcategory.where(name: 'Appliances', category_id: campus_category.id).first_or_create!(name: 'Appliances', category_id: campus_category.id)

Subcategory.where(name: 'Churches', category_id: community_category.id).first_or_create!(name: 'Churches', category_id: community_category.id)
Subcategory.where(name: 'Promotions', category_id: community_category.id).first_or_create!(name: 'Promotions', category_id: community_category.id)
Subcategory.where(name: 'Announcements', category_id: community_category.id).first_or_create!(name: 'Announcements', category_id: community_category.id)
Subcategory.where(name: 'Artists & Musicians', category_id: community_category.id).first_or_create!(name: 'Artists & Musicians', category_id: community_category.id)
Subcategory.where(name: 'Carpool & Rideshare', category_id: community_category.id).first_or_create!(name: 'Carpool & Rideshare', category_id: community_category.id)
Subcategory.where(name: 'Childcare & Babysitting', category_id: community_category.id).first_or_create!(name: 'Childcare & Babysitting', category_id: community_category.id)
Subcategory.where(name: 'Garage Sales', category_id: community_category.id).first_or_create!(name: 'Garage Sales', category_id: community_category.id)
Subcategory.where(name: 'Lost & Found', category_id: community_category.id).first_or_create!(name: 'Lost & Found', category_id: community_category.id)

Subcategory.where(name: 'Apartments', category_id: housing_category.id).first_or_create!(name: 'Apartments', category_id: housing_category.id)
Subcategory.where(name: 'Commercial', category_id: housing_category.id).first_or_create!(name: 'Commercial', category_id: housing_category.id)
Subcategory.where(name: 'Homes', category_id: housing_category.id).first_or_create!(name: 'Homes', category_id: housing_category.id)
Subcategory.where(name: 'Rentals', category_id: housing_category.id).first_or_create!(name: 'Rentals', category_id: housing_category.id)
Subcategory.where(name: 'Vacation', category_id: housing_category.id).first_or_create!(name: 'Vacation', category_id: housing_category.id)
Subcategory.where(name: 'Condos', category_id: housing_category.id).first_or_create!(name: 'Condos', category_id: housing_category.id)
Subcategory.where(name: 'Farms', category_id: housing_category.id).first_or_create!(name: 'Farms', category_id: housing_category.id)
Subcategory.where(name: 'Lands', category_id: housing_category.id).first_or_create!(name: 'Lands', category_id: housing_category.id)
Subcategory.where(name: 'Ranches', category_id: housing_category.id).first_or_create!(name: 'Ranches', category_id: housing_category.id)
Subcategory.where(name: 'Manufactured Homes', category_id: housing_category.id).first_or_create!(name: 'Manufactured Homes', category_id: housing_category.id)
Subcategory.where(name: 'Townhomes', category_id: housing_category.id).first_or_create!(name: 'Townhomes', category_id: housing_category.id)

Subcategory.where(name: 'Odd Items', category_id: h2f_category.id).first_or_create!(name: 'Odd Items', category_id: h2f_category.id)
Subcategory.where(name: 'The Rarest', category_id: h2f_category.id).first_or_create!(name: 'The Rarest', category_id: h2f_category.id)
Subcategory.where(name: 'Collectables', category_id: h2f_category.id).first_or_create!(name: 'Collectables', category_id: h2f_category.id)
Subcategory.where(name: 'Antiques', category_id: h2f_category.id).first_or_create!(name: 'Antiques', category_id: h2f_category.id)

Subcategory.where(name: 'Sale Anything', category_id: free_category.id).first_or_create!(name: 'Sale Anything', category_id: free_category.id)
Subcategory.where(name: 'Campus Life', category_id: free_category.id).first_or_create!(name: 'Campus Life', category_id: free_category.id)
Subcategory.where(name: 'Events & Community', category_id: free_category.id).first_or_create!(name: 'Events & Community', category_id: free_category.id)
Subcategory.where(name: 'Jobs pro bono', category_id: free_category.id).first_or_create!(name: 'Jobs pro bono', category_id: free_category.id)
Subcategory.where(name: 'Hard to Find', category_id: free_category.id).first_or_create!(name: 'Hard to Find', category_id: free_category.id)

Subcategory.where(name: 'Accounting', category_id: jobs_category.id).first_or_create!(name: 'Accounting', category_id: jobs_category.id)
Subcategory.where(name: 'Admin/Clerical', category_id: jobs_category.id).first_or_create!(name: 'Admin/Clerical', category_id: jobs_category.id)
Subcategory.where(name: 'Automotive', category_id: jobs_category.id).first_or_create!(name: 'Automotive', category_id: jobs_category.id)
Subcategory.where(name: 'Banking', category_id: jobs_category.id).first_or_create!(name: 'Banking', category_id: jobs_category.id)
Subcategory.where(name: 'Biotech', category_id: jobs_category.id).first_or_create!(name: 'Biotech', category_id: jobs_category.id)
Subcategory.where(name: 'Business Development', category_id: jobs_category.id).first_or_create!(name: 'Business Development', category_id: jobs_category.id)
Subcategory.where(name: 'Business Opportunity', category_id: jobs_category.id).first_or_create!(name: 'Business Opportunity', category_id: jobs_category.id)
Subcategory.where(name: 'Construction', category_id: jobs_category.id).first_or_create!(name: 'Construction', category_id: jobs_category.id)
Subcategory.where(name: 'Consultant', category_id: jobs_category.id).first_or_create!(name: 'Consultant', category_id: jobs_category.id)
Subcategory.where(name: 'Customer Service', category_id: jobs_category.id).first_or_create!(name: 'Customer Service', category_id: jobs_category.id)
Subcategory.where(name: 'Design', category_id: jobs_category.id).first_or_create!(name: 'Design', category_id: jobs_category.id)
Subcategory.where(name: 'Distribution/Shipping', category_id: jobs_category.id).first_or_create!(name: 'Distribution/Shipping', category_id: jobs_category.id)
Subcategory.where(name: 'Education', category_id: jobs_category.id).first_or_create!(name: 'Education', category_id: jobs_category.id)
Subcategory.where(name: 'Engineering', category_id: jobs_category.id).first_or_create!(name: 'Engineering', category_id: jobs_category.id)
Subcategory.where(name: 'Entry Level', category_id: jobs_category.id).first_or_create!(name: 'Entry Level', category_id: jobs_category.id)
Subcategory.where(name: 'executive', category_id: jobs_category.id).first_or_create!(name: 'executive', category_id: jobs_category.id)
Subcategory.where(name: 'Facilities', category_id: jobs_category.id).first_or_create!(name: 'Facilities', category_id: jobs_category.id)
Subcategory.where(name: 'Finance', category_id: jobs_category.id).first_or_create!(name: 'Finance', category_id: jobs_category.id)
Subcategory.where(name: 'Franchise', category_id: jobs_category.id).first_or_create!(name: 'Franchise', category_id: jobs_category.id)
Subcategory.where(name: 'General Business', category_id: jobs_category.id).first_or_create!(name: 'General Business', category_id: jobs_category.id)
Subcategory.where(name: 'General Labor', category_id: jobs_category.id).first_or_create!(name: 'General Labor', category_id: jobs_category.id)
Subcategory.where(name: 'Government/Federal', category_id: jobs_category.id).first_or_create!(name: 'Government/Federal', category_id: jobs_category.id)
Subcategory.where(name: 'Grocery Stores', category_id: jobs_category.id).first_or_create!(name: 'Grocery Stores', category_id: jobs_category.id)
Subcategory.where(name: 'Health Care', category_id: jobs_category.id).first_or_create!(name: 'Health Care', category_id: jobs_category.id)
Subcategory.where(name: 'Hospitality/Hotel', category_id: jobs_category.id).first_or_create!(name: 'Hospitality/Hotel', category_id: jobs_category.id)
Subcategory.where(name: 'Human Resources', category_id: jobs_category.id).first_or_create!(name: 'Human Resources', category_id: jobs_category.id)
Subcategory.where(name: 'Journalism/Newspaper', category_id: jobs_category.id).first_or_create!(name: 'Journalism/Newspaper', category_id: jobs_category.id)
Subcategory.where(name: 'Information Technology', category_id: jobs_category.id).first_or_create!(name: 'Information Technology', category_id: jobs_category.id)
Subcategory.where(name: 'Installation', category_id: jobs_category.id).first_or_create!(name: 'Installation', category_id: jobs_category.id)
Subcategory.where(name: 'Insurance', category_id: jobs_category.id).first_or_create!(name: 'Insurance', category_id: jobs_category.id)
Subcategory.where(name: 'Inventory', category_id: jobs_category.id).first_or_create!(name: 'Inventory', category_id: jobs_category.id)
Subcategory.where(name: 'Legal', category_id: jobs_category.id).first_or_create!(name: 'Legal', category_id: jobs_category.id)
Subcategory.where(name: 'Legal Admin', category_id: jobs_category.id).first_or_create!(name: 'Legal Admin', category_id: jobs_category.id)
Subcategory.where(name: 'Maintenance/Repair', category_id: jobs_category.id).first_or_create!(name: 'Maintenance/Repair', category_id: jobs_category.id)
Subcategory.where(name: 'Management', category_id: jobs_category.id).first_or_create!(name: 'Management', category_id: jobs_category.id)
Subcategory.where(name: 'Manufacturing', category_id: jobs_category.id).first_or_create!(name: 'Manufacturing', category_id: jobs_category.id)
Subcategory.where(name: 'Marketing', category_id: jobs_category.id).first_or_create!(name: 'Marketing', category_id: jobs_category.id)
Subcategory.where(name: 'Media', category_id: jobs_category.id).first_or_create!(name: 'Media', category_id: jobs_category.id)
Subcategory.where(name: 'Nonprofit', category_id: jobs_category.id).first_or_create!(name: 'Nonprofit', category_id: jobs_category.id)
Subcategory.where(name: 'Nurse', category_id: jobs_category.id).first_or_create!(name: 'Nurse', category_id: jobs_category.id)
Subcategory.where(name: 'Other', category_id: jobs_category.id).first_or_create!(name: 'Other', category_id: jobs_category.id)
Subcategory.where(name: 'Pharmaceutical', category_id: jobs_category.id).first_or_create!(name: 'Pharmaceutical', category_id: jobs_category.id)
Subcategory.where(name: 'Procurement', category_id: jobs_category.id).first_or_create!(name: 'Procurement', category_id: jobs_category.id)
Subcategory.where(name: 'Professional Services', category_id: jobs_category.id).first_or_create!(name: 'Professional Services', category_id: jobs_category.id)
Subcategory.where(name: 'Purchasing', category_id: jobs_category.id).first_or_create!(name: 'Purchasing', category_id: jobs_category.id)
Subcategory.where(name: 'QA/Quality Control', category_id: jobs_category.id).first_or_create!(name: 'QA/Quality Control', category_id: jobs_category.id)
Subcategory.where(name: 'Real Estate', category_id: jobs_category.id).first_or_create!(name: 'Real Estate', category_id: jobs_category.id)
Subcategory.where(name: 'Research', category_id: jobs_category.id).first_or_create!(name: 'Research', category_id: jobs_category.id)
Subcategory.where(name: 'Restaurant', category_id: jobs_category.id).first_or_create!(name: 'Restaurant', category_id: jobs_category.id)
Subcategory.where(name: 'Retail', category_id: jobs_category.id).first_or_create!(name: 'Retail', category_id: jobs_category.id)
Subcategory.where(name: 'Sales', category_id: jobs_category.id).first_or_create!(name: 'Sales', category_id: jobs_category.id)
Subcategory.where(name: 'Science', category_id: jobs_category.id).first_or_create!(name: 'Science', category_id: jobs_category.id)
Subcategory.where(name: 'Skilled Labor - Trades', category_id: jobs_category.id).first_or_create!(name: 'Skilled Labor - Trades', category_id: jobs_category.id)
Subcategory.where(name: 'Social Services', category_id: jobs_category.id).first_or_create!(name: 'Social Services', category_id: jobs_category.id)
Subcategory.where(name: 'Strategy/Planning', category_id: jobs_category.id).first_or_create!(name: 'Strategy/Planning', category_id: jobs_category.id)
Subcategory.where(name: 'Supply Chain', category_id: jobs_category.id).first_or_create!(name: 'Supply Chain', category_id: jobs_category.id)
Subcategory.where(name: 'Telecommunications', category_id: jobs_category.id).first_or_create!(name: 'Telecommunications', category_id: jobs_category.id)
Subcategory.where(name: 'Training', category_id: jobs_category.id).first_or_create!(name: 'Training', category_id: jobs_category.id)
Subcategory.where(name: 'Transportation', category_id: jobs_category.id).first_or_create!(name: 'Transportation', category_id: jobs_category.id)
Subcategory.where(name: 'Veterinary Services', category_id: jobs_category.id).first_or_create!(name: 'Veterinary Services', category_id: jobs_category.id)
Subcategory.where(name: 'Warehouse', category_id: jobs_category.id).first_or_create!(name: 'Warehouse', category_id: jobs_category.id)

Subcategory.where(name: 'Accounting', category_id: talent_category.id).first_or_create!(name: 'Accounting', category_id: talent_category.id)
Subcategory.where(name: 'Admin/Clerical', category_id: talent_category.id).first_or_create!(name: 'Admin/Clerical', category_id: talent_category.id)
Subcategory.where(name: 'Automotive', category_id: talent_category.id).first_or_create!(name: 'Automotive', category_id: talent_category.id)
Subcategory.where(name: 'Banking', category_id: talent_category.id).first_or_create!(name: 'Banking', category_id: talent_category.id)
Subcategory.where(name: 'Biotech', category_id: talent_category.id).first_or_create!(name: 'Biotech', category_id: talent_category.id)
Subcategory.where(name: 'Business Development', category_id: talent_category.id).first_or_create!(name: 'Business Development', category_id: talent_category.id)
Subcategory.where(name: 'Business Opportunity', category_id: talent_category.id).first_or_create!(name: 'Business Opportunity', category_id: talent_category.id)
Subcategory.where(name: 'Construction', category_id: talent_category.id).first_or_create!(name: 'Construction', category_id: talent_category.id)
Subcategory.where(name: 'Consultant', category_id: talent_category.id).first_or_create!(name: 'Consultant', category_id: talent_category.id)
Subcategory.where(name: 'Customer Service', category_id: talent_category.id).first_or_create!(name: 'Customer Service', category_id: talent_category.id)
Subcategory.where(name: 'Design', category_id: talent_category.id).first_or_create!(name: 'Design', category_id: talent_category.id)
Subcategory.where(name: 'Distribution/Shipping', category_id: talent_category.id).first_or_create!(name: 'Distribution/Shipping', category_id: talent_category.id)
Subcategory.where(name: 'Education', category_id: talent_category.id).first_or_create!(name: 'Education', category_id: talent_category.id)
Subcategory.where(name: 'Engineering', category_id: talent_category.id).first_or_create!(name: 'Engineering', category_id: talent_category.id)
Subcategory.where(name: 'Entry Level', category_id: talent_category.id).first_or_create!(name: 'Entry Level', category_id: talent_category.id)
Subcategory.where(name: 'executive', category_id: talent_category.id).first_or_create!(name: 'executive', category_id: talent_category.id)
Subcategory.where(name: 'Facilities', category_id: talent_category.id).first_or_create!(name: 'Facilities', category_id: talent_category.id)
Subcategory.where(name: 'Finance', category_id: talent_category.id).first_or_create!(name: 'Finance', category_id: talent_category.id)
Subcategory.where(name: 'Franchise', category_id: talent_category.id).first_or_create!(name: 'Franchise', category_id: talent_category.id)
Subcategory.where(name: 'General Business', category_id: talent_category.id).first_or_create!(name: 'General Business', category_id: talent_category.id)
Subcategory.where(name: 'General Labor', category_id: talent_category.id).first_or_create!(name: 'General Labor', category_id: talent_category.id)
Subcategory.where(name: 'Government/Federal', category_id: talent_category.id).first_or_create!(name: 'Government/Federal', category_id: talent_category.id)
Subcategory.where(name: 'Grocery Stores', category_id: talent_category.id).first_or_create!(name: 'Grocery Stores', category_id: talent_category.id)
Subcategory.where(name: 'Health Care', category_id: talent_category.id).first_or_create!(name: 'Health Care', category_id: talent_category.id)
Subcategory.where(name: 'Hospitality/Hotel', category_id: talent_category.id).first_or_create!(name: 'Hospitality/Hotel', category_id: talent_category.id)
Subcategory.where(name: 'Human Resources', category_id: talent_category.id).first_or_create!(name: 'Human Resources', category_id: talent_category.id)
Subcategory.where(name: 'Journalism/Newspaper', category_id: talent_category.id).first_or_create!(name: 'Journalism/Newspaper', category_id: talent_category.id)
Subcategory.where(name: 'Information Technology', category_id: talent_category.id).first_or_create!(name: 'Information Technology', category_id: talent_category.id)
Subcategory.where(name: 'Installation', category_id: talent_category.id).first_or_create!(name: 'Installation', category_id: talent_category.id)
Subcategory.where(name: 'Insurance', category_id: talent_category.id).first_or_create!(name: 'Insurance', category_id: talent_category.id)
Subcategory.where(name: 'Inventory', category_id: talent_category.id).first_or_create!(name: 'Inventory', category_id: talent_category.id)
Subcategory.where(name: 'Legal', category_id: talent_category.id).first_or_create!(name: 'Legal', category_id: talent_category.id)
Subcategory.where(name: 'Legal Admin', category_id: talent_category.id).first_or_create!(name: 'Legal Admin', category_id: talent_category.id)
Subcategory.where(name: 'Maintenance/Repair', category_id: talent_category.id).first_or_create!(name: 'Maintenance/Repair', category_id: talent_category.id)
Subcategory.where(name: 'Management', category_id: talent_category.id).first_or_create!(name: 'Management', category_id: talent_category.id)
Subcategory.where(name: 'Manufacturing', category_id: talent_category.id).first_or_create!(name: 'Manufacturing', category_id: talent_category.id)
Subcategory.where(name: 'Marketing', category_id: talent_category.id).first_or_create!(name: 'Marketing', category_id: talent_category.id)
Subcategory.where(name: 'Media', category_id: talent_category.id).first_or_create!(name: 'Media', category_id: talent_category.id)
Subcategory.where(name: 'Nonprofit', category_id: talent_category.id).first_or_create!(name: 'Nonprofit', category_id: talent_category.id)
Subcategory.where(name: 'Nurse', category_id: talent_category.id).first_or_create!(name: 'Nurse', category_id: talent_category.id)
Subcategory.where(name: 'Other', category_id: talent_category.id).first_or_create!(name: 'Other', category_id: talent_category.id)
Subcategory.where(name: 'Pharmaceutical', category_id: talent_category.id).first_or_create!(name: 'Pharmaceutical', category_id: talent_category.id)
Subcategory.where(name: 'Procurement', category_id: talent_category.id).first_or_create!(name: 'Procurement', category_id: talent_category.id)
Subcategory.where(name: 'Professional Services', category_id: talent_category.id).first_or_create!(name: 'Professional Services', category_id: talent_category.id)
Subcategory.where(name: 'Purchasing', category_id: talent_category.id).first_or_create!(name: 'Purchasing', category_id: talent_category.id)
Subcategory.where(name: 'QA/Quality Control', category_id: talent_category.id).first_or_create!(name: 'QA/Quality Control', category_id: talent_category.id)
Subcategory.where(name: 'Real Estate', category_id: talent_category.id).first_or_create!(name: 'Real Estate', category_id: talent_category.id)
Subcategory.where(name: 'Research', category_id: talent_category.id).first_or_create!(name: 'Research', category_id: talent_category.id)
Subcategory.where(name: 'Restaurant', category_id: talent_category.id).first_or_create!(name: 'Restaurant', category_id: talent_category.id)
Subcategory.where(name: 'Retail', category_id: talent_category.id).first_or_create!(name: 'Retail', category_id: talent_category.id)
Subcategory.where(name: 'Sales', category_id: talent_category.id).first_or_create!(name: 'Sales', category_id: talent_category.id)
Subcategory.where(name: 'Science', category_id: talent_category.id).first_or_create!(name: 'Science', category_id: talent_category.id)
Subcategory.where(name: 'Skilled Labor - Trades', category_id: talent_category.id).first_or_create!(name: 'Skilled Labor - Trades', category_id: talent_category.id)
Subcategory.where(name: 'Social Services', category_id: talent_category.id).first_or_create!(name: 'Social Services', category_id: talent_category.id)
Subcategory.where(name: 'Strategy/Planning', category_id: talent_category.id).first_or_create!(name: 'Strategy/Planning', category_id: talent_category.id)
Subcategory.where(name: 'Supply Chain', category_id: talent_category.id).first_or_create!(name: 'Supply Chain', category_id: talent_category.id)
Subcategory.where(name: 'Telecommunications', category_id: talent_category.id).first_or_create!(name: 'Telecommunications', category_id: talent_category.id)
Subcategory.where(name: 'Training', category_id: talent_category.id).first_or_create!(name: 'Training', category_id: talent_category.id)
Subcategory.where(name: 'Transportation', category_id: talent_category.id).first_or_create!(name: 'Transportation', category_id: talent_category.id)
Subcategory.where(name: 'Veterinary Services', category_id: talent_category.id).first_or_create!(name: 'Veterinary Services', category_id: talent_category.id)
Subcategory.where(name: 'Warehouse', category_id: talent_category.id).first_or_create!(name: 'Warehouse', category_id: talent_category.id)

Subcategory.where(name: 'Strictly Platonic', category_id: personals_category.id).first_or_create!(name: 'Strictly Platonic', category_id: personals_category.id)
Subcategory.where(name: 'Women / Women', category_id: personals_category.id).first_or_create!(name: 'Women / Women', category_id: personals_category.id)
Subcategory.where(name: 'Women / Men', category_id: personals_category.id).first_or_create!(name: 'Women / Men', category_id: personals_category.id)
Subcategory.where(name: 'Men / Women', category_id: personals_category.id).first_or_create!(name: 'Men / Women', category_id: personals_category.id)
Subcategory.where(name: 'Men / Men', category_id: personals_category.id).first_or_create!(name: 'Men / Men', category_id: personals_category.id)
Subcategory.where(name: 'Misc Romance', category_id: personals_category.id).first_or_create!(name: 'Misc Romance', category_id: personals_category.id)
Subcategory.where(name: 'Casual Encounters', category_id: personals_category.id).first_or_create!(name: 'Casual Encounters', category_id: personals_category.id)
Subcategory.where(name: 'Missed Connections', category_id: personals_category.id).first_or_create!(name: 'Missed Connections', category_id: personals_category.id)
Subcategory.where(name: 'Purely about Sex', category_id: personals_category.id).first_or_create!(name: 'Purely about Sex', category_id: personals_category.id)

Subcategory.where(name: 'Home & Garden', category_id: sale_category.id).first_or_create!(name: 'Home & Garden', category_id: sale_category.id)
Subcategory.where(name: 'Clothing & Accessories', category_id: sale_category.id).first_or_create!(name: 'Clothing & Accessories', category_id: sale_category.id)
Subcategory.where(name: 'Flowers & Gifts', category_id: sale_category.id).first_or_create!(name: 'Flowers & Gifts', category_id: sale_category.id)
Subcategory.where(name: 'Computers', category_id: sale_category.id).first_or_create!(name: 'Computers', category_id: sale_category.id)
Subcategory.where(name: 'Electronics', category_id: sale_category.id).first_or_create!(name: 'Electronics', category_id: sale_category.id)
Subcategory.where(name: 'Fragrances & Beauty', category_id: sale_category.id).first_or_create!(name: 'Fragrances & Beauty', category_id: sale_category.id)
Subcategory.where(name: 'Jewelry & Watches', category_id: sale_category.id).first_or_create!(name: 'Jewelry & Watches', category_id: sale_category.id)
Subcategory.where(name: 'Sports & Outdoors', category_id: sale_category.id).first_or_create!(name: 'Sports & Outdoors', category_id: sale_category.id)
Subcategory.where(name: 'Toys & Baby', category_id: sale_category.id).first_or_create!(name: 'Toys & Baby', category_id: sale_category.id)
Subcategory.where(name: 'Automotive', category_id: sale_category.id).first_or_create!(name: 'Automotive', category_id: sale_category.id)
Subcategory.where(name: 'DVD', category_id: sale_category.id).first_or_create!(name: 'DVD', category_id: sale_category.id)
Subcategory.where(name: 'Music', category_id: sale_category.id).first_or_create!(name: 'Music', category_id: sale_category.id)
Subcategory.where(name: 'Books', category_id: sale_category.id).first_or_create!(name: 'Books', category_id: sale_category.id)
Subcategory.where(name: 'Appliances', category_id: sale_category.id).first_or_create!(name: 'Appliances', category_id: sale_category.id)
Subcategory.where(name: 'Video Games', category_id: sale_category.id).first_or_create!(name: 'Video Games', category_id: sale_category.id)
Subcategory.where(name: 'Industrial', category_id: sale_category.id).first_or_create!(name: 'Industrial', category_id: sale_category.id)
Subcategory.where(name: 'Tickets', category_id: sale_category.id).first_or_create!(name: 'Tickets', category_id: sale_category.id)
Subcategory.where(name: 'Musical Instruments', category_id: sale_category.id).first_or_create!(name: 'Musical Instruments', category_id: sale_category.id)
Subcategory.where(name: 'Pets', category_id: sale_category.id).first_or_create!(name: 'Pets', category_id: sale_category.id)

Subcategory.where(name: 'Accountant', category_id: services_category.id).first_or_create!(name: 'Accountant', category_id: services_category.id)
Subcategory.where(name: 'Architecture', category_id: services_category.id).first_or_create!(name: 'Architecture', category_id: services_category.id)
Subcategory.where(name: 'Artists', category_id: services_category.id).first_or_create!(name: 'Artists', category_id: services_category.id)
Subcategory.where(name: 'Barber', category_id: services_category.id).first_or_create!(name: 'Barber', category_id: services_category.id)
Subcategory.where(name: 'Beauty Salons', category_id: services_category.id).first_or_create!(name: 'Beauty Salons', category_id: services_category.id)
Subcategory.where(name: 'Building Remodelling', category_id: services_category.id).first_or_create!(name: 'Building Remodelling', category_id: services_category.id)
Subcategory.where(name: 'Business Planner', category_id: services_category.id).first_or_create!(name: 'Business Planner', category_id: services_category.id)
Subcategory.where(name: 'Taxi Cab/UBER', category_id: services_category.id).first_or_create!(name: 'Taxi Cab/UBER', category_id: services_category.id)
Subcategory.where(name: 'Car Rental', category_id: services_category.id).first_or_create!(name: 'Car Rental', category_id: services_category.id)
Subcategory.where(name: 'Chef', category_id: services_category.id).first_or_create!(name: 'Chef', category_id: services_category.id)
Subcategory.where(name: 'Cleaning Services / Maids', category_id: services_category.id).first_or_create!(name: 'Cleaning Services / Maids', category_id: services_category.id)
Subcategory.where(name: 'Home Decor', category_id: services_category.id).first_or_create!(name: 'Home Decor', category_id: services_category.id)
Subcategory.where(name: 'Fitness Instructor', category_id: services_category.id).first_or_create!(name: 'Fitness Instructor', category_id: services_category.id)
Subcategory.where(name: 'Elderly Care', category_id: services_category.id).first_or_create!(name: 'Elderly Care', category_id: services_category.id)
Subcategory.where(name: 'IT / Programmer', category_id: services_category.id).first_or_create!(name: 'IT / Programmer', category_id: services_category.id)
Subcategory.where(name: 'Grant Writer', category_id: services_category.id).first_or_create!(name: 'Grant Writer', category_id: services_category.id)
Subcategory.where(name: 'Health Spa', category_id: services_category.id).first_or_create!(name: 'Health Spa', category_id: services_category.id)
Subcategory.where(name: 'Lawn Care', category_id: services_category.id).first_or_create!(name: 'Lawn Care', category_id: services_category.id)
Subcategory.where(name: 'Legal Services', category_id: services_category.id).first_or_create!(name: 'Legal Services', category_id: services_category.id)
Subcategory.where(name: 'Limousine', category_id: services_category.id).first_or_create!(name: 'Limousine', category_id: services_category.id)
Subcategory.where(name: 'Repair / Handyman', category_id: services_category.id).first_or_create!(name: 'Repair / Handyman', category_id: services_category.id)
Subcategory.where(name: 'Marketing Firm', category_id: services_category.id).first_or_create!(name: 'Marketing Firm', category_id: services_category.id)
Subcategory.where(name: 'Non Profit', category_id: services_category.id).first_or_create!(name: 'nonprofit', category_id: services_category.id)
Subcategory.where(name: 'Home Security', category_id: services_category.id).first_or_create!(name: 'Home Security', category_id: services_category.id)
Subcategory.where(name: 'Structural Engineer', category_id: services_category.id).first_or_create!(name: 'Structural Engineering', category_id: services_category.id)
Subcategory.where(name: 'Home Remodelling', category_id: services_category.id).first_or_create!(name: 'Home Remodelling', category_id: services_category.id)
Subcategory.where(name: 'Auto Repair', category_id: services_category.id).first_or_create!(name: 'Auto Repair', category_id: services_category.id)
Subcategory.where(name: 'Tutoring/Education', category_id: services_category.id).first_or_create!(name: 'Tutoring/Education', category_id: services_category.id)
Subcategory.where(name: 'Website Designer', category_id: services_category.id).first_or_create!(name: 'Website Designer', category_id: services_category.id)
Subcategory.where(name: 'Plumber', category_id: services_category.id).first_or_create!(name: 'Plumber', category_id: services_category.id)
Subcategory.where(name: 'Appliance Repair', category_id: services_category.id).first_or_create!(name: 'Appliance Repair', category_id: services_category.id)
Subcategory.where(name: 'Dog Walker', category_id: services_category.id).first_or_create!(name: 'Dog Walker', category_id: services_category.id)
Subcategory.where(name: 'Pressure Washing', category_id: services_category.id).first_or_create!(name: 'Pressure Washing', category_id: services_category.id)
Subcategory.where(name: 'Computer Repair', category_id: services_category.id).first_or_create!(name: 'Computer Repair', category_id: services_category.id)
Subcategory.where(name: 'Auto Insurance', category_id: services_category.id).first_or_create!(name: 'Auto Insurance', category_id: services_category.id)
Subcategory.where(name: 'Small Construction', category_id: services_category.id).first_or_create!(name: 'Small Construction', category_id: services_category.id)
Subcategory.where(name: 'Life Insurance', category_id: services_category.id).first_or_create!(name: 'Life Insurance', category_id: services_category.id)
Subcategory.where(name: 'Mortgage Refinance', category_id: services_category.id).first_or_create!(name: 'Mortgage Refinance', category_id: services_category.id)
Subcategory.where(name: 'Photographers', category_id: services_category.id).first_or_create!(name: 'Photographers', category_id: services_category.id)
Subcategory.where(name: 'Financial Planner', category_id: services_category.id).first_or_create!(name: 'Financial Planner', category_id: services_category.id)
Subcategory.where(name: 'Music Dj & Bands', category_id: services_category.id).first_or_create!(name: 'Music Dj & Bands', category_id: services_category.id)
Subcategory.where(name: 'Moving Company', category_id: services_category.id).first_or_create!(name: 'Moving Company', category_id: services_category.id)
Subcategory.where(name: 'Dentist', category_id: services_category.id).first_or_create!(name: 'Dentist', category_id: services_category.id)
Subcategory.where(name: 'Doctors', category_id: services_category.id).first_or_create!(name: 'Doctors', category_id: services_category.id)
Subcategory.where(name: 'Party Bus', category_id: services_category.id).first_or_create!(name: 'Party Bus', category_id: services_category.id)
Subcategory.where(name: 'Pawn Shops', category_id: services_category.id).first_or_create!(name: 'Pawn Shops', category_id: services_category.id)
Subcategory.where(name: 'Gun Shops', category_id: services_category.id).first_or_create!(name: 'Gun Shops', category_id: services_category.id)
Subcategory.where(name: 'Laundromat', category_id: services_category.id).first_or_create!(name: 'Laundromat', category_id: services_category.id)
Subcategory.where(name: 'Massage Therapists', category_id: services_category.id).first_or_create!(name: 'Massage Therapists', category_id: services_category.id)
Subcategory.where(name: 'Garbage Collection', category_id: services_category.id).first_or_create!(name: 'Garbage Collection', category_id: services_category.id)
Subcategory.where(name: 'Churches', category_id: services_category.id).first_or_create!(name: 'Churches', category_id: services_category.id)
Subcategory.where(name: 'Pet Grooming', category_id: services_category.id).first_or_create!(name: 'Pet Grooming', category_id: services_category.id)
Subcategory.where(name: 'Restaurants', category_id: services_category.id).first_or_create!(name: 'Restaurants', category_id: services_category.id)
Subcategory.where(name: 'Pest Control Services', category_id: services_category.id).first_or_create!(name: 'Pest Control Services', category_id: services_category.id)
Subcategory.where(name: 'Dumpster Rental', category_id: services_category.id).first_or_create!(name: 'Dumpster Rental', category_id: services_category.id)
Subcategory.where(name: 'Reception Halls', category_id: services_category.id).first_or_create!(name: 'Reception Halls', category_id: services_category.id)
Subcategory.where(name: 'Roofing Contractors', category_id: services_category.id).first_or_create!(name: 'Roofing Contractors', category_id: services_category.id)
Subcategory.where(name: 'Tow Truck Service', category_id: services_category.id).first_or_create!(name: 'Tow Truck Service', category_id: services_category.id)
Subcategory.where(name: 'Cash Services', category_id: services_category.id).first_or_create!(name: 'Cash Services', category_id: services_category.id)

Subcategory.where(name: 'Home & Garden', category_id: unboxing_category.id).first_or_create!(name: 'Home & Garden', category_id: unboxing_category.id)
Subcategory.where(name: 'Clothing & Accessories', category_id: unboxing_category.id).first_or_create!(name: 'Clothing & Accessories', category_id: unboxing_category.id)
Subcategory.where(name: 'Computers', category_id: unboxing_category.id).first_or_create!(name: 'Computers', category_id: unboxing_category.id)
Subcategory.where(name: 'Electronics', category_id: unboxing_category.id).first_or_create!(name: 'Electronics', category_id: unboxing_category.id)
Subcategory.where(name: 'Jewelry & Watches', category_id: unboxing_category.id).first_or_create!(name: 'Jewelry & Watches', category_id: unboxing_category.id)
Subcategory.where(name: 'Sports & Outdoors', category_id: unboxing_category.id).first_or_create!(name: 'Sports & Outdoors', category_id: unboxing_category.id)
Subcategory.where(name: 'Toys & Baby', category_id: unboxing_category.id).first_or_create!(name: 'Toys & Baby', category_id: unboxing_category.id)
Subcategory.where(name: 'Appliances', category_id: unboxing_category.id).first_or_create!(name: 'Appliances', category_id: unboxing_category.id)
Subcategory.where(name: 'Musical Instruments', category_id: unboxing_category.id).first_or_create!(name: 'Musical Instruments', category_id: unboxing_category.id)
