#!/bin/bash
cd /home/ec2-user/ruby-on-rails

# install JS runtime
yum install nodejs

# install Ruby Version Manager (rvm)
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm requirements
rvm install 2.3.0

# Install app dependencies
gem install rails
bundle install

# Install app DB migrations
rake db:migrate
