---
- hosts: all
  vars:
    rd_dns: mariadb
  become: true
  gather_facts: false

  pre_tasks:
    - name: Update dependencies via apt-get
      raw: sudo apt-get clean && apt-get autoclean && sudo apt autoremove -y && sudo apt-get update -y

    - name: Installing awscli, https transport, build-essential, Python & PIP
      raw: sudo apt-get install -y awscli apt-transport-https build-essential python-minimal python-setuptools python-pip software-properties-common

  tasks:
    - name: Install system dependencies
      apt:
        pkg:
          - git
          - curl
          - libcurl4-openssl-dev
          - libffi-dev
          - libreadline6-dev
          - s3fs
          - zlib1g
          - zlib1g-dev
        state: present
    - name: Mount S3 Bucket
        command: >
          s3fs mybucket /path/to/mountpoint -o passwd_file=${HOME}/.passwd-s3fs