describe('Bottom menu static page CRUD...', function () {

    it('...reads static page content.', function () {
        cy.visit('')
        cy.get('#myNavbar > ul > li > a').contains('About Us').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Career With Us').click()
        cy.visit('career')
        cy.get('#myNavbar > ul > li > a').contains('About Us').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('About Us').click()
        cy.visit('about')
        cy.get('#myNavbar > ul > li > a').contains('About Us').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Newsletter').click()
        cy.visit('howitworks/index')
        cy.get('#myNavbar > ul > li > a').contains('About Us').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('How It Works').click()
        cy.visit('howitworks/index')
        cy.get('#myNavbar > ul > li > a').contains('About Us').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Prices').click()
        cy.visit('prices/index')

        cy.get('#myNavbar > ul > li > a').contains('Legal').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Terms of Service').click()
        cy.visit('terms')
        cy.get('#myNavbar > ul > li > a').contains('Legal').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Privacy Policy').click()
        cy.visit('privacy')
        cy.get('#myNavbar > ul > li > a').contains('Legal').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Posting Terms of Use').click()
        cy.visit('postterm')

        cy.get('#myNavbar > ul > li > a').contains('Help').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('FAQs').click()
        cy.visit('faq')
        cy.get('#myNavbar > ul > li > a').contains('Help').click()
        cy.get('#myNavbar > ul > li.dropup.open > ul > li > a').contains('Safety Tips').click()
        cy.visit('safetytips')

        cy.visit('')
    })
})
