describe('Test Comment system', function() {
    it('...submit and view a comment on a Posting.', function() {
    cy.visit('')
    cy.get('.container > #navbar > .nav > li:nth-child(1) > a').click()
    cy.get('.row > .col-sm-12 > .form-group > .input-group > #user_email').type('test@test.com')
    cy.get('.row > .col-sm-12 > .form-group > .input-group > #user_password').type('testtest')
    cy.get('fieldset > .row > .col-sm-12 > .form-group > .btn').click()
    cy.visit('')
    cy.get('body > .jbar').click()
    cy.get('.container > #navbar > .nav > li > .post').click()
    cy.get('.panel-body > #new_listing > .input-group > .form-control > #listing_category_id').click()
    cy.get('.panel-body > #new_listing > .input-group > .form-control > #listing_category_id').select('1')
    cy.get('.panel-body > #new_listing > .input-group > .form-control > #listing_subcategory_id').select('1')
    cy.get('.panel > .panel-body > #new_listing > .input-group > #listing_price').type('1.23')
    cy.get('.panel > .panel-body > #new_listing > .input-group > #listing_city').type('Testtown')
    cy.get('.panel > .panel-body > #new_listing > .input-group > #listing_zipcode').type('33612')
    cy.get('.panel > .panel-body > #new_listing > .input-group > #listing_media').type('C:\...\24fps.mp4')
    cy.get('.panel-body > #new_listing > .input-group > .actions > #listings_submit').click()
    cy.visit('/listings/1')
    cy.get('.container_12 > .grid_6 > .comments > #new_comment > #comment_body').click()
    cy.get('.container_12 > .grid_6 > .comments > #new_comment > #submit-btn').click()
    cy.visit('/listings/1')

 })
})
