version: "3"

services:
  cachet:
    image: cachethq/docker:2.3.15
    ports:
      - ${CACHET_HOSTPORT}:8000
    environment:
      - DB_DRIVER=${CACHET_DB_DRIVER}
      - DB_HOST=${CACHET_DB_HOST}
      - DB_PORT=${CACHET_DB_PORT}
      - DB_DATABASE=${CACHET_DB_DATABASE}
      - DB_USERNAME=${CACHET_DB_USERNAME}
      - DB_PASSWORD=${CACHET_DB_PASSWORD}
      - DB_PREFIX=${CACHET_DB_PREF}
      - APP_KEY=${CACHET_APP_KEY}
      - APP_LOG=${CACHET_APP_ERRLOG}
      - DEBUG=${CACHET_DEBUG}
    restart: on-failure
    networks:
      - connechub
networks:
  connechub:
    external:
      name: connechub